BINDIR = '/usr/local/bin'
BLOCK_MESSAGE_KEYS = []
BUILD_TYPE = 'app'
BUNDLE_NAME = 'pebble.pbw'
DEFINES = ['RELEASE']
LIBDIR = '/usr/local/lib'
LIB_DIR = 'node_modules'
MESSAGE_KEYS = {}
MESSAGE_KEYS_HEADER = '/pebble/build/include/message_keys.auto.h'
NODE_PATH = '/home/pebble/.pebble-sdk/SDKs/current/node_modules'
PEBBLE_SDK_COMMON = '/home/pebble/.pebble-sdk/SDKs/current/sdk-core/pebble/common'
PEBBLE_SDK_ROOT = '/home/pebble/.pebble-sdk/SDKs/current/sdk-core/pebble'
PREFIX = '/usr/local'
PROJECT_INFO = {u'sdkVersion': u'3', u'projectType': u'native', u'uuid': u'9538bece-9027-4f6f-81b1-a44620085992', u'appKeys': {}, u'companyName': u'Max Baeumle/James Fowler', 'messageKeys': {}, u'targetPlatforms': [u'aplite', u'basalt'], u'capabilities': [u''], u'versionLabel': u'2.7', u'longName': u'Diary Face', u'shortName': u'Diary Face', u'watchapp': {u'watchface': True}, u'resources': {u'media': [{u'type': u'png', u'name': u'PEBBLE', u'file': u'images/pebble.png'}, {u'type': u'png', u'name': u'ENTRY_5', u'file': u'images/entry-5.png'}, {u'type': u'png', u'name': u'ENTRY_4', u'file': u'images/entry-4.png'}, {u'type': u'png', u'name': u'ENTRY_3', u'file': u'images/entry-3.png'}, {u'type': u'png', u'name': u'ENTRY_2', u'file': u'images/entry-2.png'}, {u'type': u'png', u'name': u'ENTRY_0', u'file': u'images/entry-0.png'}, {u'type': u'png', u'name': u'ENTRY_1', u'file': u'images/entry-1.png'}, {u'type': u'png', u'name': u'WATCH_BATTERY_CHARGE_ICON', u'file': u'images/watch-battery-charge.png'}, {u'type': u'png', u'name': u'PHONE_BATTERY_CHARGE_ICON', u'file': u'images/phone-battery-charge.png'}, {u'type': u'font', u'name': u'FONT_ROBOTO_CONDENSED_21', u'file': u'fonts/Roboto-Condensed.ttf'}, {u'type': u'font', u'characterRegex': u'[:0-9]', u'name': u'FONT_ROBOTO_BOLD_SUBSET_49', u'file': u'fonts/Roboto-Bold.ttf'}, {u'type': u'png', u'name': u'WATCH_BATTERY_ICON', u'file': u'images/watch-battery-normal.png'}, {u'type': u'png', u'name': u'PHONE_BATTERY_ICON', u'file': u'images/phone-battery-normal.png'}, {u'type': u'png', u'name': u'IMAGE_STATUS_1', u'file': u'images/status1.png'}, {u'type': u'png', u'name': u'IMAGE_STATUS_2', u'file': u'images/status2.png'}]}}
REQUESTED_PLATFORMS = [u'aplite', u'basalt']
RESOURCES_JSON = [{u'type': u'png', u'name': u'PEBBLE', u'file': u'images/pebble.png'}, {u'type': u'png', u'name': u'ENTRY_5', u'file': u'images/entry-5.png'}, {u'type': u'png', u'name': u'ENTRY_4', u'file': u'images/entry-4.png'}, {u'type': u'png', u'name': u'ENTRY_3', u'file': u'images/entry-3.png'}, {u'type': u'png', u'name': u'ENTRY_2', u'file': u'images/entry-2.png'}, {u'type': u'png', u'name': u'ENTRY_0', u'file': u'images/entry-0.png'}, {u'type': u'png', u'name': u'ENTRY_1', u'file': u'images/entry-1.png'}, {u'type': u'png', u'name': u'WATCH_BATTERY_CHARGE_ICON', u'file': u'images/watch-battery-charge.png'}, {u'type': u'png', u'name': u'PHONE_BATTERY_CHARGE_ICON', u'file': u'images/phone-battery-charge.png'}, {u'type': u'font', u'name': u'FONT_ROBOTO_CONDENSED_21', u'file': u'fonts/Roboto-Condensed.ttf'}, {u'type': u'font', u'characterRegex': u'[:0-9]', u'name': u'FONT_ROBOTO_BOLD_SUBSET_49', u'file': u'fonts/Roboto-Bold.ttf'}, {u'type': u'png', u'name': u'WATCH_BATTERY_ICON', u'file': u'images/watch-battery-normal.png'}, {u'type': u'png', u'name': u'PHONE_BATTERY_ICON', u'file': u'images/phone-battery-normal.png'}, {u'type': u'png', u'name': u'IMAGE_STATUS_1', u'file': u'images/status1.png'}, {u'type': u'png', u'name': u'IMAGE_STATUS_2', u'file': u'images/status2.png'}]
SANDBOX = False
SUPPORTED_PLATFORMS = ['emery', 'chalk', 'aplite', 'diorite', 'basalt']
TARGET_PLATFORMS = ['basalt', 'aplite']
TIMESTAMP = 1637689739
USE_GROUPS = True
VERBOSE = 0
WEBPACK = '/home/pebble/.pebble-sdk/SDKs/current/node_modules/.bin/webpack'
